export const AUTH_TOKENS = {
  LOGIN_LOCAL_USE_CASE: 'AUTH/LOGIN_LOCAL_USE_CASE',
  REFRESH_TOKEN_USE_CASE: 'AUTH/REFRESH_TOKEN_USE_CASE',
  LOGOUT_USE_CASE: 'AUTH/LOGOUT_USE_CASE',
  REGISTER_LOCAL_USE_CASE: 'AUTH/REGISTER_LOCAL_USE_CASE',
  VERIFY_EMAIL_USE_CASE: 'AUTH/VERIFY_EMAIL_USE_CASE',
  RESEND_VERIFICATION_USE_CASE: 'AUTH/RESEND_VERIFICATION_USE_CASE',
  REQUEST_PASSWORD_RESET_USE_CASE: 'AUTH/REQUEST_PASSWORD_RESET_USE_CASE',
  RESET_PASSWORD_USE_CASE: 'AUTH/RESET_PASSWORD_USE_CASE',
  AUTHENTICATE_WITH_GOOGLE_WEB_USE_CASE:
    'AUTH/AUTHENTICATE_WITH_GOOGLE_WEB_USE_CASE',
  AUTHENTICATE_WITH_GOOGLE_MOBILE_USE_CASE:
    'AUTH/AUTHENTICATE_WITH_GOOGLE_MOBILE_USE_CASE',
  GET_CURRENT_PROFILE_USE_CASE: 'AUTH/GET_CURRENT_PROFILE_USE_CASE',
  UPDATE_USER_ROLE_USE_CASE: 'AUTH/UPDATE_USER_ROLE_USE_CASE',
  USER_REPOSITORY: 'AUTH/USER_REPOSITORY',
  CREDENTIALS_REPOSITORY: 'AUTH/CREDENTIALS_REPOSITORY',
  VERIFICATION_TOKEN_REPOSITORY: 'AUTH/VERIFICATION_TOKEN_REPOSITORY',
  PASSWORD_RESET_TOKEN_REPOSITORY: 'AUTH/PASSWORD_RESET_TOKEN_REPOSITORY',
  REFRESH_SESSION_REPOSITORY: 'AUTH/REFRESH_SESSION_REPOSITORY',
  GOOGLE_AUTH_VERIFIER: 'AUTH/GOOGLE_AUTH_VERIFIER',
  TOKEN_ISSUER: 'AUTH/TOKEN_ISSUER',
  RESEND_VERIFICATION_THROTTLE_STORE: 'AUTH/RESEND_VERIFICATION_THROTTLE_STORE',
} as const;
