export const SHARED_TOKENS = {
  DOMAIN_EVENT_BUS: 'SHARED/DOMAIN_EVENT_BUS',
  PASSWORD_HASHER: 'SHARED/PASSWORD_HASHER',
  PASSWORD_POLICY_VALIDATOR: 'SHARED/PASSWORD_POLICY_VALIDATOR',
  TOKEN_KEY_MANAGEMENT: 'SHARED/TOKEN_KEY_MANAGEMENT',
} as const;
