export const SHARED_TOKENS = {
  APP_CONFIG: 'SHARED/APP_CONFIG',
  PRISMA_SERVICE: 'SHARED/PRISMA_SERVICE',
  PASSWORD_HASHER: 'SHARED/PASSWORD_HASHER',
  PASSWORD_POLICY_VALIDATOR: 'SHARED/PASSWORD_POLICY_VALIDATOR',
  TOKEN_KEY_MANAGEMENT: 'SHARED/TOKEN_KEY_MANAGEMENT',
  DOMAIN_EVENT_BUS: 'SHARED/DOMAIN_EVENT_BUS',
  MAIL_TRANSPORT: 'SHARED/MAIL_TRANSPORT',
  NODEMAILER_TRANSPORTER: 'SHARED/NODEMAILER_TRANSPORTER',
  AUTH_EMAIL_SERVICE: 'SHARED/AUTH_EMAIL_SERVICE',
} as const;
